name: nuget cahce

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: local
    permissions:
      packages: write
      contents: read
   
    env:
      BUILD_PATH: ${{ github.workspace }}\_build
      # NUGET_PACKAGES: ${{ github.workspace }}\.github\nuget-packages
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1  
      
    - name: Clean solution
      working-directory: ${{ github.workspace }}
      run: msbuild /t:clean

    - name: Clean NuGet cache
      run: |
        nuget locals all -clear

    - name: Restore NuGet packages with msbuild
      working-directory: ${{ github.workspace }}
      run: nuget restore EFContextMock.sln
    
      
    - name: Build with msbuild
      working-directory: ${{ github.workspace }}
      run: msbuild.exe EFContextMock.sln /p:DeployOnBuild=true /p:PublishProfile=Publish /p:PublishUrl="${{ env.BUILD_PATH }}" /p:VersionSuffix="${{ github.run_number }}"


    # - name: Compress Web Build artifact
    #   run: Compress-Archive -Path "${{ env.BUILD_PATH }}" -DestinationPath "${{ env.BUILD_PATH }}.zip"


    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: "${{ env.BUILD_PATH }}.zip"     

    - run: Get-ChildItem
    

  # Deploy-to-IIS-Server:
  
  #   runs-on: Windows
  #   needs: build

  #   steps:
  #   - name: Download artifact
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: Bundle
  #       path: ${{ github.workspace }}/_build
