name: Artifact_id

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Enter the run ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Get Artifact ID
        id: get_artifact_id
        run: |
          RUN_ID=${{ github.event.inputs.run_id }}
          ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
                       "https://api.github.com/repos/abhishekmachag/msbuild/actions/runs/$RUN_ID/artifacts" \
                       | jq -r '.artifacts[0].id')
          echo "Artifact ID for run $RUN_ID: $ARTIFACT_ID"
          echo "::set-output name=artifact_id::$ARTIFACT_ID"

      - name: Use Artifact ID
        run: |
          # Now you can use the artifact_id in subsequent steps
          ARTIFACT_ID=${{ steps.get_artifact_id.outputs.artifact_id }}
          echo "Using Artifact ID: $ARTIFACT_ID"
          # Add your commands here that use the artifact ID


















# name: GetUserInputPipeline-download-artifact

# on:
#   workflow_dispatch:
#     inputs:
#       artifact_id:
#         description: 'Artifact ID to download'
#         required: true

# jobs:
#   download-artifact:
#     runs-on: ubuntu-latest

#     steps:            
#       - name: Download Artifact
#         run: |
#           artifact_id=${{ github.event.inputs.artifact_id }}
#           curl -L \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             "https://api.github.com/repos/abhishekmachag/msbuild/actions/artifacts/${artifact_id}/zip" -o artifacts.zip
#       - name: List Artifact Contents
#         run: ls

#       - name: Upload Artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: my-artifact
#           path: ./artifacts.zip
