name: Download and Upload Artifact

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Enter the run ID for the workflow'
        required: true


jobs:
  get_artifact_id:
    runs-on: ubuntu-latest

    steps:
    - name: Get Artifact ID
      id: get_artifact
      run: |
        run_number="${{ github.event.workflow_run.id }}"
        repository="msbuild"
        token="${{ secrets.GH_TOKEN }}"
        
        # Get the list of artifacts for a specific run
        artifacts_url="https://api.github.com/repos/$repository/actions/runs/$run_number/artifacts"
        artifact_id=$(curl -sH "Authorization: Bearer $token" $artifacts_url | jq -r '.artifacts[0].id')

        echo "Artifact ID for run $run_number: $artifact_id"
        
        echo "##[set-output name=artifact_id;]$artifact_id"

    - name: Use Artifact ID
      run: |
        artifact_id="${{ steps.get_artifact.outputs.artifact_id }}"
        echo "Using Artifact ID: $artifact_id"





        

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Get Artifact ID
#         run: |
#           RUN_ID=${{ github.event.inputs.run_id }}
#           ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
#                        "https://api.github.com/repos/abhishekmachag/msbuild/actions/runs/$RUN_ID/artifacts" \
#                        | jq -r '.artifacts[0].id')
#           echo "Artifact ID for run $RUN_ID: $ARTIFACT_ID"
#           echo "::set-output name=artifact_id::$ARTIFACT_ID"

#       - name: Download Artifact
#         run: |
#           ARTIFACT_ID=${{ needs.get-artifact-id.outputs.artifact_id }}
#           curl -L \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             "https://api.github.com/repos/abhishekmachag/msbuild/actions/artifacts/$ARTIFACT_ID/zip" -o artifacts.zip

#       - name: List Artifact
#         run: ls

#       - name: Upload Artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: my-artifact
#           path: ./artifacts.zip

