name: GetUserInputPipeline-retrieve-artifacts

on:
  workflow_dispatch:
    inputs:
      run_number:
        description: 'Run number of the build to retrieve'
        required: true

jobs:
  retrieve-build:
    runs-on: ubuntu-latest

    env:
      COMMIT_SHA: ''
      BRANCH_NAME: ''

    steps:
      - name: Retrieve build information
        id: get_build
        run: |
          api_url="https://api.github.com/repos/abhishekmachag/msbuild/actions/runs/${{ github.event.inputs.run_number }}"
          response=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "$api_url")
          echo "COMMIT_SHA=${response | jq -r '.head_commit.id'}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${response | jq -r '.head_branch'}" >> $GITHUB_ENV

      - name: Checkout specific commit
        uses: actions/checkout@v2
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Archive build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: retrieved-build
          path: artifacts
