name: GetUserInputPipeline-download-artifact

on:
  workflow_dispatch:
    # inputs:
    #   artifact_id:
    #     description: 'Artifact ID to download'
    #     required: true

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:

    - name: Get Artifact ID
      id: get_artifact_id
      run: |
        run_number=${{ github.run_number }}
        response=$(curl -s \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          "https://api.github.com/repos/abhishekmachag/msbuild/actions/runs/${run_number}/artifacts")
    
            artifact_id=$(echo $response | jq -r '.artifacts[0].id')
            echo "Artifact ID: $artifact_id"


          # RUN_ID=7152588810
          # ARTIFACT_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          #              "https://api.github.com/repos/abhishekmachag/msbuild/actions/runs/${{ github.run_number }}/artifacts" \
          #              | jq -r '.artifacts[0].id')
          # echo "Artifact ID for run ${{ github.run_number }}: $ARTIFACT_ID"
            
      # - name: Download Artifact
      #   run: |
      #     artifact_id=${{ github.event.inputs.artifact_id }}
      #     curl -L \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       "https://api.github.com/repos/abhishekmachag/msbuild/actions/artifacts/${artifact_id}/zip" -o artifacts.zip
      # - name: List Artifact Contents
      #   run: ls

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: ./artifacts.zip
