name: resusable-workflow-ubuntu

on: 
  push:
    branches: ["master"]
  workflow_call:
  workflow_dispatch:
jobs:
  # build:
  #   runs-on: windows-2019
  #   env:
  #     BUILD_PATH: ${{ github.workspace }}\_build
  #   steps:
  #   - name: Checkout First1 Repository
  #     uses: actions/checkout@v3
  #     with:
  #       repository: abhishekmachag/msbuild
  #       ref: master
  #       path: ${{ github.workspace }}/msbuild
        
  #   - run: Get-ChildItem
    
  #   - name: Setup MSBuild
  #     uses: microsoft/setup-msbuild@v1
    
  #   - name: Setup NuGet
  #     uses: NuGet/setup-nuget@v1  
  
  #   - name: Restore NuGet packages with msbuild
  #     working-directory: ${{ github.workspace }}\msbuild
  #     run: nuget restore EFContextMock.sln
      
  #   - name: Build with msbuild
  #     working-directory: ${{ github.workspace }}\msbuild
  #     run: msbuild.exe EFContextMock.sln /p:DeployOnBuild=true /p:PublishProfile=Publish /p:PublishUrl="${{ env.BUILD_PATH }}" /p:VersionSuffix="${{ github.run_number }}" /p:IsPackaging=true

  #   - name: Compress Web Build artifact
  #     run: Compress-Archive -Path "${{ env.BUILD_PATH }}" -DestinationPath "${{ env.BUILD_PATH }}.zip" 

  #   - name: Upload artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: Artifacts
  #       path: "${{ env.BUILD_PATH }}.zip"    


  deploy:
    runs-on: windows-2019
    # needs: build
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: Artifacts
      #     path: ${{ github.workspace }}/build

      # - name: Expand Build artifact
      #   run: Expand-Archive -Path "${{ github.workspace }}\build\_build.zip" -DestinationPath "${{ github.workspace }}\build" -Force
        
      - name: PowerShell Session to Copy Build
        run: |
              Enable-PSRemoting -Force
              Set-Item WSMan:\localhost\Client\TrustedHosts -Value "34.244.15.14" -Force
              # set-item WSMan:\localhost\Client\TrustedHosts "*"
              $username = "Administrator"
              $password = "6ppr0KasqshE8qDIMF9WdTz=IUBC.3-)"
              $securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
              $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)
              Invoke-Command -ComputerName 34.244.15.14 -Credential $credential -ScriptBlock {Remove-Item -Path "C:\temp\*" -Recurse -Force}
              $psSession = New-PSSession -ComputerName 34.244.15.14 -Credential $credential
              Copy-Item "${{ github.workspace }}/build/_build/*" -Destination "C:\temp" -ToSession $psSession -Recurse -Force
              Exit-PSSession

      # - name: Remove temporary files
      #   run: Remove-Item -Path ${{ github.workspace }}/build -Recurse -Force
              
      # - name: Deploying tthe Build Artifacts to Root Directory
      #   run: |
      #     $username = "Administrator"
      #     $password = "6ppr0KasqshE8qDIMF9WdTz=IUBC.3-)" | ConvertTo-SecureString -AsPlainText -Force
      #     $credential = New-Object System.Management.Automation.PSCredential($username, $password)
  
      #     # Perform actions in the remote session
      #     Invoke-Command -ComputerName 34.244.15.14 -Credential $credential -ScriptBlock {
      #         Remove-Item -Path "C:\temp\*" -Recurse -Force
      #     }

          
      # - name: Expand WebAPI Build artifact
      #   run: Expand-Archive -Path "${{ github.workspace }}\_webapi_build\WebApiBuild.zip" -DestinationPath "${{ github.workspace }}\_webapi_build" -Force

      # - name: Remove existing files for WebAPI
      #   run: Remove-Item -Path "C:\inetpub\wwwroot\bundle3\*" -Recurse -Force

      # - name: Copy new files for WebAPI
      #   run: Copy-Item -Path "${{ github.workspace }}\_webapi_build\WebApiBuild\*" -Destination C:\inetpub\wwwroot\bundle3 -Recurse -Force

      # - name: Remove temporary files for WebAPI
      #   run: Remove-Item -Path ${{ github.workspace }}\_webapi_build -Recurse -Force
